import { useStore } from "../Context/store";
import { Link } from "react-router-dom";
import { FaArrowRight, FaShoppingBag } from "react-icons/fa";

export default function Cart() {
  const { cart, subtotal, removeFromCart, updateQuantity } = useStore();
  const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
  return <main className="min-h-[70vh] py-10 md:py-16"><div className="page-shell"><p className="section-kicker">Your selection</p><h1 className="mt-3 text-5xl font-extrabold tracking-[-.055em] md:text-7xl">The bag.</h1>
    {cart.length === 0 ? <div className="mt-10 flex min-h-[360px] flex-col items-center justify-center rounded-[2rem] border border-dashed border-[#18201d]/20 bg-white p-8 text-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#eef4df] text-2xl text-[#527026]"><FaShoppingBag /></span><h2 className="mt-6 text-2xl font-bold">Your bag is beautifully empty.</h2><p className="mt-2 text-[#717b75]">Take a look around—we saved the good stuff for you.</p><Link to="/store" className="mt-7 flex items-center gap-2 rounded-full bg-[#18201d] px-6 py-3 font-bold text-white">Explore the edit <FaArrowRight /></Link></div> :
    <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-[2rem] border border-[#18201d]/8 bg-white px-5 sm:px-8">{cart.map(item => <article key={item.id} className="grid grid-cols-[96px_1fr] gap-4 border-b border-[#18201d]/8 py-6 last:border-0 sm:flex sm:items-center sm:gap-5 sm:py-7"><div className="grid h-24 w-24 place-items-center rounded-2xl bg-[#eef0e8] p-2 sm:h-32 sm:w-32 sm:p-3"><img src={item.thumbnail} alt={item.title} className="h-full w-full object-contain" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-[#71805c] sm:text-xs">Aven pick</p><h2 className="mt-1 line-clamp-2 text-base font-bold sm:text-lg">{item.title}</h2><p className="mt-1 font-display text-base font-extrabold sm:mt-2 sm:text-lg">{currency.format(item.price)}</p><p className="mt-1 text-xs text-[#717b75] sm:text-sm">Item total: {currency.format(item.price * item.qty)}</p><button type="button" onClick={() => removeFromCart(item.id)} className="mt-2 text-xs font-bold text-[#a05a52] hover:underline sm:mt-3">Remove</button></div><div className="col-span-2 flex w-fit items-center rounded-full border border-[#18201d]/12 p-1 sm:col-auto"><button type="button" onClick={() => updateQuantity(item.id,"decrease")} className="grid h-10 w-10 place-items-center rounded-full hover:bg-[#eef0e8] sm:h-11 sm:w-11" aria-label="Decrease quantity">−</button><span className="w-9 text-center text-sm font-bold">{item.qty}</span><button type="button" onClick={() => updateQuantity(item.id,"increase")} className="grid h-10 w-10 place-items-center rounded-full bg-[#18201d] text-white sm:h-11 sm:w-11" aria-label="Increase quantity">+</button></div></article>)}</section>
      <aside className="h-fit rounded-[2rem] bg-[#17201c] p-7 text-white lg:sticky lg:top-24"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d9ff8c]">Order summary</p><h2 className="mt-3 text-2xl font-bold">Almost yours.</h2><div className="mt-8 space-y-4 text-sm text-white/60"><div className="flex justify-between"><span>Subtotal</span><span className="text-white">{currency.format(subtotal)}</span></div><div className="flex justify-between"><span>Shipping</span><span className="text-[#d9ff8c]">Free</span></div></div><div className="mt-6 flex justify-between border-t border-white/15 pt-6 font-bold"><span>Total</span><span>{currency.format(subtotal)}</span></div><p className="mt-4 text-xs leading-5 text-white/45">Checkout is not included in this frontend demo.</p><Link to="/store" className="mt-4 block text-center text-sm font-semibold text-white/60 hover:text-white">Keep shopping</Link></aside>
    </div>}
  </div></main>;
}
