import React, { useContext } from "react";
import { Link } from "react-router-dom";
import { store } from "../Context/StoreContext";
import { FaArrowRight, FaShoppingBag } from "react-icons/fa";

export default function Cart() {
  const { cart, qtyHandler } = useContext(store);
  return <main className="min-h-[70vh] py-10 md:py-16"><div className="page-shell"><p className="section-kicker">Your selection</p><h1 className="mt-3 text-5xl font-extrabold tracking-[-.055em] md:text-7xl">The bag.</h1>
    {cart.length === 0 ? <div className="mt-10 flex min-h-[360px] flex-col items-center justify-center rounded-[2rem] border border-dashed border-[#18201d]/20 bg-white p-8 text-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#eef4df] text-2xl text-[#527026]"><FaShoppingBag /></span><h2 className="mt-6 text-2xl font-bold">Your bag is beautifully empty.</h2><p className="mt-2 text-[#717b75]">Take a look around—we saved the good stuff for you.</p><Link to="/store" className="mt-7 flex items-center gap-2 rounded-full bg-[#18201d] px-6 py-3 font-bold text-white">Explore the edit <FaArrowRight /></Link></div> :
    <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-[2rem] border border-[#18201d]/8 bg-white px-5 sm:px-8">{cart.map(item => <article key={item.id} className="flex flex-col gap-5 border-b border-[#18201d]/8 py-7 last:border-0 sm:flex-row sm:items-center"><div className="grid h-32 w-full shrink-0 place-items-center rounded-2xl bg-[#eef0e8] p-3 sm:w-32"><img src={item.thumbnail} alt={item.title} className="h-full w-full object-contain" /></div><div className="flex-1"><p className="text-xs font-bold uppercase tracking-wider text-[#71805c]">Nivara pick</p><h2 className="mt-1 text-lg font-bold">{item.title}</h2><p className="mt-2 font-display text-lg font-extrabold">${item.price}</p><button className="mt-3 text-xs font-bold text-[#a05a52] hover:underline">Remove</button></div><div className="flex w-fit items-center rounded-full border border-[#18201d]/12 p-1"><button onClick={() => qtyHandler(item.id,"dec")} className="grid h-9 w-9 place-items-center rounded-full hover:bg-[#eef0e8]" aria-label="Decrease quantity">−</button><span className="w-9 text-center text-sm font-bold">{item.qty}</span><button onClick={() => qtyHandler(item.id,"inc")} className="grid h-9 w-9 place-items-center rounded-full bg-[#18201d] text-white" aria-label="Increase quantity">+</button></div></article>)}</section>
      <aside className="h-fit rounded-[2rem] bg-[#17201c] p-7 text-white lg:sticky lg:top-24"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d9ff8c]">Order summary</p><h2 className="mt-3 text-2xl font-bold">Almost yours.</h2><div className="mt-8 space-y-4 text-sm text-white/60"><div className="flex justify-between"><span>Subtotal</span><span className="text-white">Calculated at checkout</span></div><div className="flex justify-between"><span>Shipping</span><span className="text-[#d9ff8c]">Complimentary</span></div></div><div className="mt-6 border-t border-white/15 pt-6"><p className="text-xs leading-5 text-white/45">Taxes and final total are confirmed securely at checkout.</p></div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-[#d9ff8c] py-4 font-bold text-[#17201c]">Continue to checkout <FaArrowRight /></button><Link to="/store" className="mt-4 block text-center text-sm font-semibold text-white/60 hover:text-white">Keep shopping</Link></aside>
    </div>}
  </div></main>;
}
