import React from "react";
import { FaArrowRight, FaEnvelope, FaMapMarkerAlt } from "react-icons/fa";

export default function Contact() {
  return <main className="py-10 md:py-16"><div className="page-shell grid overflow-hidden rounded-[2rem] border border-[#18201d]/8 bg-white lg:grid-cols-[.85fr_1.15fr]">
    <section className="soft-grid bg-[#17201c] p-8 text-white md:p-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d9ff8c]">Connect with us</p><h1 className="mt-5 text-5xl font-extrabold tracking-[-.055em] md:text-6xl">We’re all ears.</h1><p className="mt-5 max-w-md leading-7 text-white/55">Questions, feedback, or just want help finding the right thing? Drop us a note.</p><div className="mt-12 space-y-5 text-sm"><p className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/10 text-[#d9ff8c]"><FaEnvelope /></span>hello@nivara.shop</p><p className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/10 text-[#d9ff8c]"><FaMapMarkerAlt /></span>New Delhi, India</p></div></section>
    <section className="p-8 md:p-14"><h2 className="text-2xl font-extrabold">Tell us what’s on your mind.</h2><p className="mt-2 text-sm text-[#758079]">We usually reply within one business day.</p><form className="mt-8 grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Your name<input type="text" placeholder="Aarav Mehta" className="mt-2 w-full rounded-2xl border border-[#18201d]/12 bg-[#f8f8f3] px-4 py-3.5 font-normal outline-none focus:border-[#638331]" /></label><label className="text-sm font-bold">Email address<input type="email" placeholder="aarav@example.com" className="mt-2 w-full rounded-2xl border border-[#18201d]/12 bg-[#f8f8f3] px-4 py-3.5 font-normal outline-none focus:border-[#638331]" /></label></div><label className="text-sm font-bold">How can we help?<select className="mt-2 w-full rounded-2xl border border-[#18201d]/12 bg-[#f8f8f3] px-4 py-3.5 font-normal outline-none"><option>Product question</option><option>Order support</option><option>Returns</option><option>Something else</option></select></label><label className="text-sm font-bold">Message<textarea rows="5" placeholder="Write your message here..." className="mt-2 w-full resize-none rounded-2xl border border-[#18201d]/12 bg-[#f8f8f3] px-4 py-3.5 font-normal outline-none focus:border-[#638331]" /></label><button type="button" className="flex w-fit items-center gap-3 rounded-full bg-[#d9ff8c] px-7 py-3.5 font-bold text-[#18201d]">Send your note <FaArrowRight /></button></form></section>
  </div></main>;
}
